### ISSUE TITLE
Doesn't appear to be working?

### ISSUE THREAD

**Issue by CoreyCorza** [CreativeDesigner3D/Library_Toy_Box#1]
![image](https://user-images.githubusercontent.com/40785775/82751873-975d9200-9dfd-11ea-8e95-0078c596dca9.png)

What version of blender was this made for?
Im using 2.82a

**Comment by CreativeDesigner3D** [comment]
This is part of a proposal I am putting together for the Blender Development team. I will be releasing information about this add-on this week. It currently only works in a custom build of Blender, but I am hoping to make this available in the 2.9x series.
